[package]
name = "simple-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.30", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["display"] }
